version: "3.9"

services:
  loving-backend:
    build: .
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
